[package]
name = "qsh"
version = "0.1.0"
edition = "2024"
authors = ["Leyvi Rose <leyvirose@gmail.com>"]

[lib]
name = "libqsh"
path = "src/lib/lib.rs"

[dependencies]
bincode = { version = "2.0.1", features = ["std", "derive", "alloc", "bincode_derive", "serde"] }
bitflags = { version = "2.9.0", features = ["core", "serde"] }
blake3 = { version = "1.6.1", default-features = false }
config = { version = "0.15.9", default-features = false, features = ["toml"] }
kyberlib = { version = "0.0.6", features = ["nasm-rs"], optional = true }
lz4_flex = { version = "0.11.3", default-features = false, optional = true }
rand = "0.9.0"
rand_chacha = { version = "0.9.0", features = ["os_rng"] }
rand_core = { version = "0.9.3", features = ["os_rng"] }
thiserror = { version = "2.0.12", default-features = false }

[features]
default = ["lz4_flex", "kyberlib"]
